### ISSUE TITLE
Delay zwischen Interaktion und Aktion

### ISSUE THREAD

**Issue by RedstoneFuture** [RedstoneWorld/RedAction#1]
Timings | ohne WorldEdit:
https://timings.aikar.co/?id=d68d00e6aca145299c33372b078cf815

Timings | statt Actionbar-Nachrichten Verwendung von Chat-Nachrichten + mit WorldEdit:
https://timings.aikar.co/?id=1b36c49f5e334bfa9dad857fa9279311

Es liegt wohl nicht an der Anzahl der Actions.

**ursprüngliche Idee zum Fixen:**
Man teilt die Actions in Synchron (Cancel erlaubt) und Asynchron (ohne die Cancel-Option). Die Synchron-Actions öffnen eh nur GUIs - da stört keine halbe Sekunde Verzögerung. Bei Nutzen der Hebel merkt man das viel mehr - und viel öfter. Hier muss ich nichts canceln.

**Comment by RedstoneFuture** [comment]
[config - lange Version.zip](https://github.com/RedstoneWorld/RedAction/files/4095960/config.-.lange.Version.zip)

**Comment by Phoenix616** [comment]
Timings sind sehr kurz und nicht wirklich aussagekäftig in dem Fall. Besser wäre nen Spark/Warmroast Profiler stack dafür.

Werd mal testweise die nicht-cancel Aktionen in nem separate Thread async filtern lassen aber bezweifle etwas dass das (außer durch den Fakt dass es weniger Aktionen sind die direkt beim Event ausgeführt werden) wirklich eine Auswirkung auf das eigentliche Problem hat. Möglicherweise ist die Lösung auch einfach nur das Event zu canceln wenn eine Aktion mit cancel gematcht ist und alle anderen Befehle dann nach dem Event und einen Tick später auszuführen.

**Comment by Phoenix616** [comment]
[Build 24](https://ci.minebench.de/job/RedAction/24/) ist vom async-search Branch.

**Comment by RedstoneFuture** [comment]
Zumindest kann ich nun bei einer 3325 Zeilen langen Config nicht durch Spamen einer Aktion innerhalb einer Minute die TPS unter 19,5 bringen (geschweige auf 10) - was schon ein sehr beachtlicher Fortschritt ist.

Ich teste mal in Ruhe weiter und lasse das neu-eingerichtete Plugin wieder auf die Server.

Vielen Dank!!
